module.exports = {
  Create: require('./Create'),
  CreateDraft: require('./CreateDraft'),
  GetDraft: require('./GetDraft'),
  SignUp: require('./SignUp'),
  LogIn: require('./LogIn'),
  Update: require('./Update'),
  Update: require('./Update'),
  GetUsers: require('./GetUsers'),
  GetById: require('./GetById'),
  Remove: require('./Remove'),
  RestorePassword: require('./RestorePassword'),
  ResetPassword: require('./ResetPassword'),
  Confirm: require('./Confirm'),
}